config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
    }
    devise_scope :user do
      get 'addresses', to: 'users/registrations#new_address'
      post 'addresses', to: 'users/registrations#create_address'
      get 'creditcards', to: 'users/registrations#new_creditcard'
      post 'creditcards', to: 'users/registrations#create_creditcard'
    end
  root 'items#index'

  resources :items do 
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
    
    member do
      get 'purchase_confirm'
      post 'purchase'
    end
  end

  resources :users, only: [] do
    collection do
      get 'mypage'
      get 'identification'
      get 'logout'
      resources :credit_cards, only:[:new, :show, :create, :destroy]
      resources :addresses, only:[:new, :edit, :create, :update, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :nickname, presence: true, uniqueness: true
  validates :last_name, :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :last_name_kana, :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :password, presence: true, length: { minimum: 7 }, format: { with: /(?=.*\d+.*)(?=.*[a-zA-Z]+.*)./ }
  validates :birth_date, presence: true

  has_many :purchases
  has_many :items
  has_many :comments
  has_one :credit_card
  has_one :address
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end


  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    @address[:user_id] = @user.id
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    session["address"] = @address.attributes
    @creditcard = @user.build_credit_card
    render :new_creditcard
  end


  def create_creditcard
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(session["address"])
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    if params[:payjpToken].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        card: params[:payjpToken],
        # metadata: {user_id: current_user.id}
        description: 'furima-test', 
        email: @user.email,
      )
    end

    @card = CreditCard.new(customer_id: customer.id, card_id: customer.default_card)
    @card[:user_id] = @user.id
    unless @card.valid?
      flash.now[:alert] = @card.errors.full_messages
      render :new_creditcard and return
    end
    @user.build_address(@address.attributes)
    @user.build_credit_card(@card.attributes)
    if @user.save
      sign_in(:user, @user)
      redirect_to root_path
    else
      render :new
    end
  end

  
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected
  # def address_params
  #   params.require(:address).permit(:address,:postal_code, :prefecture,:city,:apartment)
  # end

  def address_params
    params.require(:address).permit(:post_code, :prefecture_id, :city, :house_number, :building_name, :phone_number)
  end

  def creditcard_params
    params.require(:creditcard).permit(:card_id,:card_year, :card_month, :card_pass,:card_company)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_root
  before_action :get_category_parents

  def identification
  end

  def mypage
  end
  
  def logout
  end
  
  private
  def move_to_root
    unless user_signed_in? 
      redirect_to root_path
    end
  end

  def get_category_parents
    @category_parent_array = Category.where(ancestry: nil)
  end
end

app/views/users/_mypage_side.html.haml
.side-content
  %nav.mypage-nav
    %ul.mypage-nav-list
      %li
        =link_to mypage_users_path, class: "mypage-nav-list-item" do
          マイページ
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          お知らせ
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          やることリスト
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          いいね！一覧
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to new_item_path, class: "mypage-nav-list-item" do
          出品する
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          出品した商品 - 出品中
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          出品した商品 - 取引中
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          出品した商品 - 売却済み
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          購入した商品 - 取引中
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          購入した商品 - 過去の取引
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          ニュース一覧
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          評価一覧
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          ガイド
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          お問い合わせ
          = icon("fas", "angle-right", class: "icon-arrow-right")
    
    %h3.mypage-nav-head-setting
      設定
    %ul.mypage-nav-list-setting
      %li
        =link_to "#", class: "mypage-nav-list-setting-item" do
          プロフィール
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        - if current_user.address.present?
          = link_to edit_address_path(current_user.address.id), class: "mypage-nav-list-setting-item" do
            発送元・お届け先住所変更
            = icon("fas", "angle-right", class: "icon-arrow-right")
        - else
          =link_to new_address_path, class: "mypage-nav-list-setting-item" do
            発送元・お届け先住所変更
            = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        - if current_user.credit_card.present?
          = link_to credit_card_path(current_user.credit_card.id), method: "get", class: "mypage-nav-list-setting-item" do
            カードの編集
            = icon("fas", "angle-right", class: "icon-arrow-right")
        - else
          = link_to new_credit_card_path, method: "get", class: "mypage-nav-list-setting-item" do
            カードの登録
            = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-setting-item" do
          メール/パスワード
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to identification_users_path, class: "mypage-nav-list-setting-item" do
          本人情報
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to "#", class: "mypage-nav-list-setting-item" do
          電話番号の確認
          = icon("fas", "angle-right", class: "icon-arrow-right")
      %li
        =link_to logout_users_path, class: "mypage-nav-list-setting-item" do
          ログアウト
          = icon("fas", "angle-right", class: "icon-arrow-right")

app/views/users/_mypage_top_main.html.haml
.main-content
  %section.user
    .user-link
      %figure
        .user-link__iconn
          = image_tag "material/icon/user_avetar.png", class:"user-link__icon"
      %h2.user-link__name
        = current_user.nickname
      .user-link__number
        評価  0  出品数  0
  %section.notification-todo
    %ul.tabs
      %li.active
        お知らせ
      %li
        やることリスト
    .tab-content-notification-todo
      %ul.notification-item-list
        %li.notification-item-link
          .notification-item-link__logo
            = image_tag "material/logo/logo.png"
          .notification-item-link__body
            .notification-item-link__body--text
              《あなた限定》ファミリーマート・ローソンのお買い物をおトクに♪ 100ポイント還元クーポン配信中！
            %time
              = icon("far", "clock", class: "icon-time")
              %span 1 時間前
          %i.icon-arrow-right
        %li.notification-item-link            
          .notification-item-link__logo
            = image_tag "material/logo/logo.png"
          .notification-item-link__body
            .notification-item-link__body--text
              《総額1億ポイントが当たる》今日の申込み完了まで抽選対象！
            %time
              = icon("far", "clock", class: "icon-time")
              %span
                1 日前
          %i.icon-arrow-right
        %li.notification-item-link
          .notification-item-link__logo
            = image_tag "material/logo/logo.png"
          .notification-item-link__body
            .notification-item-link__body--text
              《もうすぐ終了》今なら出品祭で最大3万円分ポイント当たる！
            %time
              = icon("far", "clock", class: "icon-time")
              %span
                3 日前
          %i.icon-arrow-right
        %li.notification-item-link
          .notification-item-link__logo
            = image_tag "material/logo/logo.png"
          .notification-item-link__body
            .notification-item-link__body--text
              ＼あと5日／はじめてのメルペイスマート払いで実質最大¥2,000引き！まずはエントリー
            %time
              = icon("far", "clock", class: "icon-time")
              %span 5 日前
          %i.icon-arrow-right
        %li.notification-item-link
          .notification-item-link__logo
            = image_tag "material/logo/logo.png"
          .notification-item-link__body
            .notification-item-link__body--text
              明日、P500還元クーポンの有効期限が切れます！タップして詳細を確認しましょう。
            %time
              = icon("far", "clock", class: "icon-time")
              %span 8 日前
          %i.icon-arrow-right
        %li.mypage-go-list
          =link_to "#", class: "go" do
            一覧を見る
      %ul.notification-item-list.hide
        %li.notification-item-link
          .notification-item-link__logo
            = image_tag "material/logo/logo.png"
          .notification-item-link__body
            .notification-item-link__body--text
              メールアドレスを確認してください。
            %time
              = icon("far", "clock", class: "icon-time")
              %span 1 時間前
  %section.transaction-hisory
    %h2.header
      購入した商品
    %ul.transaction-tabs
      %li.active
        取引中
      %li
        過去の取引
    .tab-content-transaction
      %ul.tab-content-transaction__now
        %li.tab-content-transaction__notfound
          = image_tag "material/logo/logo.png"
          %p
            取引中の商品がありません
      %ul.tab-content-transaction__old.hide
        %li.tab-content-transaction__notfound
          = image_tag "material/logo/logo.png"
          %p
            過去に取引した商品がありません

app/views/users/identification.html.haml
=render "items/header"
%main.mypage-contents.clearfix
  = render "mypage_side"
  .main-content
    .content-wrapper
      .contents-title
        %h2 本人情報
      .contents
        .user-datas
          .user-data
            %label お名前
            .user-link
              %p.user-link__last_name
                = current_user.last_name
              %p.user-link__first_name
                = current_user.first_name
          .user-data
            %label お名前カナ
            .user-link
              %p.user-link__last_name_kana
                = current_user.last_name_kana
              %p.user-link__first_name_kana
                = current_user.first_name_kana
          .user-data
            %label ニックネーム
            .user-link
              %p.user-link__nickname
                = current_user.nickname
          .user-data
            %label 生年月日
            .user-link
              %p.user-link__birth_date
                = current_user.birth_date
=render "items/footer"

app/views/users/logout.html.haml
=render "items/header"
%main.mypage-contents.clearfix
  = render "mypage_side"
  .main-content
    .content-wrapper
      .contents-title
        %h2 ログアウトページ
      .contents
        .logout-form
          = link_to "ログアウト", destroy_user_session_path,method: :delete, class: 'logout-btn'
=render "items/footer"

app/views/users/mypage.html.haml
=render "items/header"
%main.mypage-contents.clearfix
  = render "mypage_side"
  = render "mypage_top_main"
=render "items/footer"