config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
    }
    devise_scope :user do
      get 'addresses', to: 'users/registrations#new_address'
      post 'addresses', to: 'users/registrations#create_address'
      get 'creditcards', to: 'users/registrations#new_creditcard'
      post 'creditcards', to: 'users/registrations#create_creditcard'
    end
  root 'items#index'

  resources :items do 
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
    
    member do
      get 'purchase_confirm'
      post 'purchase'
    end
  end

  resources :users, only: [] do
    collection do
      get 'mypage'
      get 'identification'
      get 'logout'
      resources :credit_cards, only:[:new, :show, :create, :destroy]
      resources :addresses, only:[:new, :edit, :create, :update, :destroy]
    end
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:edit, :update, :destroy]
  before_action :get_category_parents, only: [:new, :edit]
  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    if @address.save
      redirect_to mypage_users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to mypage_users_path
    else
      render :edit
    end
  end

  def destroy
    if @address.destroy
      redirect_to mypage_users_path
    else
      render :edit
    end
  end

  private
  def address_params
    params.require(:address).permit(:post_code, :prefecture_id, :city, :house_number, :building_name, :phone_number).merge(user_id: current_user.id)
  end

  def set_address
    @address = Address.find_by(user_id: current_user.id)
  end

  def get_category_parents
    @category_parent_array = Category.where(ancestry: nil)
  end
end

app/views/addresses/_form.html.haml
.main-content
  .content-wrapper
    .contents-title
      %h2
        発送元・お届け先住所変更
    .contents
      .form-area
        = form_with model: @address, class: 'address-form', html: { name: "inputForm" } do |f|
          .address-form__input-field
            .label
              = f.label :郵便番号, class: 'label'
              %span
                必須
            .form
              = f.text_field :post_code, type: 'text', class: 'text-field', placeholder: '例）123-4567', maxlength: "8"
          .address-form__input-field
            .label
              = f.label :都道府県, class: 'label'
              %span
                必須
            .form
              = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt:"選択してください"},{class:"text-field"}
          .address-form__input-field
            .label
              = f.label :市区町村, class: 'label'
              %span
                必須
            .form
              = f.text_field :city, type: 'text', class: 'text-field', placeholder: '例）横浜市緑区'
          .address-form__input-field
            .label
              = f.label :番地, class: 'label'
              %span
                必須
            .form
              = f.text_field :house_number, type: 'text', class: 'text-field', placeholder: '例）青山1-1-1'
          .address-form__input-field
            .label
              = f.label :建物名, class: 'label'
              %span.any
                任意
            .form
              = f.text_field :building_name, type: 'text', class: 'text-field', placeholder: '例）柳ビル103'
          .address-form__input-field
            .label
              = f.label :電話番号, class: 'label'
              %span.any
                任意
            .form
              = f.text_field :phone_number, type: 'text', class: 'text-field', placeholder: '例）09012345678'
          .address-form__submit-btn
            .action
              = f.submit '登録', class: 'address-submit-btn'
            .action
              - if @address.persisted?
                = link_to "削除", address_path(@address), method: :delete, class: "btn--gray"

app/views/addresses/edit.html.haml
=render "items/header"
%main.mypage-contents.clearfix
  = render "users/mypage_side"
  = render "form", locals: @address
=render "items/footer"

app/views/addresses/new.html.haml
=render "items/header"
%main.mypage-contents.clearfix
  = render "users/mypage_side"
  = render "form", locals: @address
=render "items/footer"