config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
    }
    devise_scope :user do
      get 'addresses', to: 'users/registrations#new_address'
      post 'addresses', to: 'users/registrations#create_address'
      get 'creditcards', to: 'users/registrations#new_creditcard'
      post 'creditcards', to: 'users/registrations#create_creditcard'
    end
  root 'items#index'

  resources :items do 
    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'category/get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
    
    member do
      get 'purchase_confirm'
      post 'purchase'
    end
  end

  resources :users, only: [] do
    collection do
      get 'mypage'
      get 'identification'
      get 'logout'
      resources :credit_cards, only:[:new, :show, :create, :destroy]
      resources :addresses, only:[:new, :edit, :create, :update, :destroy]
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :size
  belongs_to_active_hash :condition
  belongs_to_active_hash :shipping_fee
  belongs_to_active_hash :handling_time
  belongs_to :category
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, :category_id, :size_id, :prefecture_id, :condition_id, :shipping_fee_id, :handling_time_id, :status, :images, presence: true
  validates :description, presence: true, length: { maximum: 1000 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :set_item, except: [:index, :new, :create, :get_category_children, :get_category_grandchildren]
  before_action :get_category_parents, only: [:index, :new, :show]

  def index
    @new_items = Item.where(status: true).order("created_at DESC").limit(5)
  end

  def show
  end

  def new
    @item = Item.new
    @item.images.new
    #データベースから、親カテゴリーのみ抽出し、配列化
    @category_parent_array = Category.where(ancestry: nil)
  end

  # 以下全て、formatはjsonのみ
  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find(params[:parent_id]).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to item_path(@item.id)
    else
      flash[:notice] = '商品の出品に失敗しました。登録内容を確認してください。'
      redirect_to new_item_path
    end 
  end

  def edit
    unless current_user.id == @item.user_id
      redirect_to root_path
    end
  end

  def update
    if @item.update(item_update_params)
      redirect_to item_path(@item.id)
    else
      flash[:notice] = '商品情報の更新に失敗しました。登録内容を確認してください。'
      @item = Item.find(params[:id])
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :edit
    end
  end

  def purchase_confirm
    card = get_my_payjp_token
    if card.present?
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      @card = customer.cards.retrieve(card.card_id)
    end
  end

  def purchase
    begin
      card = get_my_payjp_token
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      Payjp::Charge.create(
        amount: @item.price,
        customer: card.customer_id,
        currency: 'jpy',
      )
    rescue StandardError => e
      flash[:notice] = '申し訳ありません。商品の購入でエラーが発生しました。カスタマーサービスまでお問い合わせください。'
      redirect_to confirm_item_path(@item.id)
    end

    if @item.update_attribute(:status, 0)
      render "purchase_completed"
    else
      redirect_to confirm_item_path(@item.id)
    end
end

  private
  def item_params
    params.require(:item).permit(
      :name, 
      :price, 
      :description, 
      :size_id, 
      :category_id, 
      :brand, 
      :condition_id, 
      :shipping_fee_id, 
      :handling_time_id, 
      :prefecture_id, 
      :status, 
      images_attributes: [:image]
    ).merge(user_id: current_user.id)
  end

  def item_update_params
    params.require(:item).permit(
      :name, 
      :price, 
      :description, 
      :size_id, 
      :category_id, 
      :brand, 
      :condition_id, 
      :shipping_fee_id, 
      :handling_time_id, 
      :prefecture_id, 
      :status, 
      images_attributes: [:image, :_destroy, :id]
    ).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def get_my_payjp_token
    CreditCard.find_by(user_id: current_user.id)
  end

  def get_category_parents
    @category_parent_array = Category.where(ancestry: nil)
  end
end

app/views/items/_footer.html.haml
.footer
  %ul.contents
    %li.content
      %h3.content__header
        FURIMAについて
      %ul
        %li 
          = link_to "会社概要", "#"
        %li
          = link_to "プライバシーポリシー", "#"
        %li 
          = link_to "FURIMA利用規約", "#"
        %li 
          = link_to "ポイントに関する特約", "#"
    %li.content
      %h3.content__header
        FURIMAを見る
      %ul
        %li 
          = link_to "カテゴリー一覧", "#"
        %li 
          = link_to "ブランド一覧", "#"
    %li.content
      %h3.content__header
        ヘルプ＆ガイド
      %ul
        %li 
          =link_to "FURIMAガイド", "#"
        %li 
          = link_to "FURIMAロゴ利用ガイドライン","#"
        %li 
          = link_to "お知らせ", "#"

  .footer__logo
    = link_to image_tag("material/logo/logo-white.png"), items_path

  %p ©FURIMA

  = link_to new_item_path do
    .display__btn
      %p 出品する
      = image_tag asset_path("material/icon/icon_camera.png")

app/views/items/_form.html.haml
.exhibit__page
  = render 'new_header'
  .exhibit__page__main
    .exhibit__page__main__contents
      = form_for @item, html:{class:"form-content"} do |f|
        %h3.exhibit__page__main__contents__message
          商品の情報を入力
        .img-form
          %label.img__upload__text
            出品画像
            %span.form--caution 
              必須
          %p.img__upload__comment
            最大5枚までアップロードできます
          #image-box
            #image-visible
              #previews
                - if @item.persisted? 
                  - @item.images.each_with_index do |image, i|
                    .single-box
                      = image_tag image.image.url, data: { index: i }, width: "100", height: '100', class: "preview__image"
                      .__edit-box{"data-index": i}
                        .js-edit
                          編集
                        .js-remove
                          削除
              %label#input-area
                .__cover
                  = image_tag "material/icon/icon_camera-bk.png", class: "__camera-icon"
            #input-hidden
              = f.fields_for :images do |image|
                .js-file_group{"data-index":"#{image.index}"}
                  = image.file_field :image, class: 'js-file'
                - if @item.persisted?
                  = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
              - if @item.persisted?
                .js-file_group{"data-index":"#{@item.images.count}"}
                  = file_field_tag :image, {name: "item[images_attributes][#{@item.images.count}][image]", class: 'js-file'}
        .sell--content
          .sell--content__name
            %label.sell--content__name__name
              商品名
              %span.form--caution 
                必須
            %div
              = f.text_field :name, class:"item-name__text__field", placeholder: "商品名（必須 40文字まで)"
          .sell--content__description
            %label.sell--content__description__description
              商品の説明
              %span.form--caution 
                必須
            =f.text_area :description, class:"sell--content__text__area", placeholder: '商品の説明（必須 1,000文字以内）&#13;&#10;（色、素材、重さ、定価、注意点など）&#13;&#10;&#13;&#10; 例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。'.html_safe
        .item-details
          %p.item-details__name 商品の詳細
          .item-details__form
          .item-details__form__category
            %label.item-details__form__category__name
              カテゴリー
              %span.form--caution 必須
              .select--wrap__category
                - if controller.action_name == 'new'
                  .select--wrap__category__parent
                    = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: "選択してください"}, {id: 'parent_category', class:"select--wrap__category__name"}
                    = icon('fas', 'angle-down')
                - else
                  .select--wrap__category__parent
                    = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {selected: @item.category.root_id}, {id: 'parent_category', class:"select--wrap__category__name"}
                    = icon('fas', 'angle-down')
                  .select--wrap__category__child
                    = f.collection_select :category_id, @item.category.parent.siblings, :id, :name, {selected: @item.category.parent_id}, {id: 'children_wrapper', class:"select--wrap__category__name"}
                    = icon('fas', 'angle-down')
                  .select--wrap__category__grandchild
                    = f.collection_select :category_id, @item.category.siblings, :id, :name, {selected: Category.where(params[:child_id])}, {id: 'grandchildren_wrapper', class:"select--wrap__category__name"}
                    = icon('fas', 'angle-down')
                -# %i.fas.fa-angle-down
            .item-details__form__brand
              %h3.item-details__form__brand__name
                ブランド
                %span.form--caution 任意
                .select--wrap
                  = f.text_field :brand, class:"select--wrap__default", placeholder: "例）シャネル"
            .item-details__form__size
              %label.item-details__form__size__name
                サイズ
                %span.form--caution 必須
                .select--wrap
                  = f.collection_select :size_id, Size.all, :id, :name, {prompt:"選択してください"}, {class:"select--wrap__default"}
                  %i.fas.fa-angle-down
                        
            .item-details__form__status
              %label.item-details__form__status__name
                商品の状態
                %span.form--caution 必須
                .select--wrap
                  = f.collection_select :condition_id, Condition.all, :id, :name, {prompt:"選択してください"}, {class:"select--wrap__default"}
                  %i.fas.fa-angle-down
        .delivery-form
          %p.delivery-form__about__delivery
            配送について
            =link_to "?", "#", class: 'form--question'
          -# .delivery-form__box
          .delivery-form__box__top
            %label.delivery-form__box__top__name
              配送料の負担
              %span.form--caution 必須
            .select--wrap
              = f.collection_select :shipping_fee_id, ShippingFee.all, :id, :name, {prompt:"選択してください"}, {class:"select--wrap__default"}
              %i.fas.fa-angle-down
          .delivery-form__box__middle
            %label.delivery-form__box__top__name
              発送元の地域
              %span.form--caution 必須
            .select--wrap
              = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt:"選択してください"},{class:"select--wrap__default "}
              %i.fas.fa-angle-down
          .delivery-form__box__bottom
            %label.delivery-form__box__top__name
              発送までの日数
              %span.form--caution 必須
            .select--wrap
              = f.collection_select :handling_time_id, HandlingTime.all, :id, :name, {prompt:"選択してください"}, {class:"select--wrap__default"}
              %i.fas.fa-angle-down
        .item-price
          %p.item-price__name 
            価格(300〜9,999,999)
            =link_to "?", "#", class: 'form--question'
          .item-price__form
            .item-price__form__left
              %label.item-price__form__name
                販売価格
                %span.form--caution 必須
            %span.item-price__form__right
              ¥
            .input--price 
              =f.text_field :price, class:"input--price__default", placeholder: "0"
        - unless @item.persisted?
          .item-status
            = f.hidden_field :status, value: "1"
        .submit-button
          .actions
            - if @item.persisted?
              = f.submit "更新する",class:"btn--red"
            - else
              = f.submit "出品する",class:"btn--red"
            - if @item.persisted?
              = link_to "商品を削除する", item_path(@item), method: :delete, data: {confirm: "削除しますか？"}, class: "btn--gray"
            =link_to "もどる", items_path, class:"btn--plane"
          .subimit-button__text
            禁止されている出品、
            =link_to "行為", "#", class: 'sell--content5__p__a'
            および
            =link_to "出品物", "#", class: 'sell--content5__p__a'
            を必ずご確認ください。
            =link_to "偽ブランド品", "#", class: 'sell--content5__p__a'
            や
            =link_to "盗品物", "#", class: 'sell--content5__p__a'
            の販売は犯罪であり、法律により処罰される可能性があります。また出品をもちまして、
            =link_to "加盟店規約", "#", class: 'sell--content5__p__a'
            に同意したことになります。
  = render "devise/registrations/user_footer"

app/views/items/_form_footer.html.haml
.exhibit-page__footer
  .exhibit-page__footer__content
    .exhibit-page__footer__content__main
      %ul.exhibit-page__footer__lists
        %li.exhibit-page__footer__list
          プライバシーポリシー
        %li.exhibit-page__footer__list
          メルカリ利用規約
        %li.exhibit-page__footer__list
          特定商取引に関する表記
        %p.exhibit-page__footer__copyright
          © 2019 Mercari

app/views/items/_header.html.haml
.header
  .header--inner
    .search
      %h1.search__icon
        = link_to root_path, data: {"turbolinks" => false} do
          = image_tag asset_path("material/logo/logo.png")
          -# %img{src: "assets/material/logo/logo.png"}
      .search__body
        %form
          %input.search--inner{name: "keyword", placeholder: "キーワードから探す", type: "text"}
          %button.search__button{type: "submit"}
            .button__img
              = image_tag asset_path("material/icon/icon-search 1.png")
              -# %img{src: "assets/material/icon/icon-search 1.png"}
    .nav
      %ul.nav--left
        %li.nav__category
          = link_to "カテゴリー", "#", id:"category__btn"
          .category__tree
            %ul.category__parents.display--none
              - @category_parent_array.each do |parent|
                %li.parents__item
                  = link_to "#" do
                    = parent.name
                  %ul.category__children.display--none
                    - parent.children.each do |children|
                      %li.children__item
                        = link_to "#" do
                          = children.name
                        %ul.category__grand-children.display--none
                          - children.children.each do |grand_children|
                            %li.grand-children__item
                              = link_to "#" do
                                = grand_children.name
        %li.nav__brand
          %a#brand__btn{href: "#"} ブランド
      %ul.nav--right
        - if user_signed_in?
          %li.login__form
            = link_to "サインアウト", destroy_user_session_path, method: :delete, id: "login__btn"
          %li.login__form--new
            = link_to "マイページ", mypage_users_path, id: "new__btn"
        - else
          %li.login__form
            = link_to "ログイン", new_user_session_path, id: "login__btn"
          %li.login__form--new
            = link_to "新規会員登録", new_user_registration_path, id: "new__btn"

app/views/items/_main.html.haml
.main
  %section.top
    .content
      %h2.content__subtitle
        人生を変えるフリマアプリ
      %p.content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
          フリマアプリです
      .content__btn
        = link_to image_tag("material/icon/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",class: "abtn"), "#"
        = link_to image_tag("material/icon/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg",class: "bbtn"), "#"
    .toppicture
  %section.description
    %h2.title
      FURIMAが選ばれる３つの理由
    %ul.lists
      %li.list
        .list__pict
          %span.number
            1
          = image_tag asset_path("material/pict/pict-reason-01.jpg")
        %h3.list__text
          %span
            3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__pict
          %span.number
            2
          = image_tag asset_path("material/pict/pict-reason-02.jpg")
        %h3.list__text
          %span
            シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list.list--last
        .list__pict
          %span.number
            3
          = image_tag asset_path("material/pict/pict-reason-03.jpg")
        %h3.list__text
          手数料
          %span
            業界最安
        %p.list__description
          最大3%でお得に出品&購入！
  %section.middle
    .middle__inner
      %h2.subtitle
        会員数日本一位
      %p.text
        FURIMAはフリマアプリで最も人気。
        %br
          出品・購入回数も業界最多です！
          %br
            ほしかったあの商品に出会えるかもしれません。
      .btn
        = link_to image_tag("material/icon/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",class: "abtn"), "#"
        = link_to image_tag("material/icon/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg",class: "bbtn"), "#"
  %section.features
    %h2.head
      FURIMAの特徴
    .items
      %section.item
        %figure.item__tag
          = image_tag asset_path("material/icon/icon-01.png")
        %h3.item__subtitle
          簡単に売り買いできる
        %p.item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.item
        %figure.item__tag
          = image_tag asset_path("material/icon/icon-03.png")
        %h3.item__subtitle
          売上金は即日振込みに対応
        %p.item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
      %section.item
        %figure.item__tag
          = image_tag asset_path("material/icon/icon-04.png")
        %h3.item__subtitle
          様々な支払いに対応
        %p.item__detail
          お支払いはクレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.pickupcontainer
    %h2.head
      ピックアップカテゴリー
    .productbox
      .producthead
        = link_to "#" do
          %h3.title
            新規投稿商品
      .productlists
        - if @new_items.present?
          = render partial: "new_items", collection: @new_items, as: "item"
%aside.appbanner

app/views/items/_new_header.html.haml
.exhibit__page__header
  = link_to root_path,class: 'exhibit__logo__link' do
    = image_tag "material/logo/logo.png",class:"exhibit__logo__img"

app/views/items/_new_items.html.haml
.productlist
  = link_to item_path(item.id) do
    %figure.productlist--img
      - if item.images[0].blank?
        = image_tag "material/pict/no_images.png"
      - else
        = image_tag item.images[0].image.url
    .productlist--body
      %h3.name
        = item.name
      .details
        %ul
          %li
            = item.price
          %li
            = icon("fas","star")
            1
        %p
          (税込)

app/views/items/confirm.haml
.single-container
  %header.single-header
    %h1
      =link_to root_path do
        = image_tag asset_path("material/logo/logo.png")
  .single-main
    .l-single-container
      %h2
        購入内容の確認
      .single-main__container__form__frame
        .field.item-info
          .image
            = image_tag @item.images[0].image.url
          .info
            .name
              = @item.name
            .price
              税込
              = @item.shipping_fee.name
              %span
                ¥
                = @item.price
        .field.pay-amount
          %label
            支払い金額
          .amount
            ¥
            = @item.price
        .field.credit-card
          .sub-title
            支払い方法
          - if @card.present?
            %h3
              クレジットカード情報
            .card-number
              = "**** **** **** " + @card.last4
            %h3
              カードの有効期限
            .card-exp
              = @card.exp_month.to_s 
              = "/"
              = @card.exp_year.to_s.slice(2,3)
          - else
            = link_to "クレジットカードを登録してください", new_credit_card_path

        .field.address  
          .sub-title
            配送先
          - if current_user.address.present?
            .address
              = current_user.address.post_code
              = current_user.address.prefecture.name
              = current_user.address.city
              = current_user.address.building_name
          - else
            = link_to "配送先を登録してください", new_address_path
        .field.button
          - if @card.present? && current_user.address.present? && @item.status
            = link_to "購入する", purchase_item_path, method: :post, class: "buttun purchase"
          - else
            - unless @item.status
              %span
                この商品は売却済みです。現在購入はできません。
            - if @card.blank? || current_user.address.blank?
              %span
                商品の購入には、クレジットカード、及び配送先の登録が必要です。
              = link_to "購入する", "#", class: "buttun purchase disabled"
  = render "devise/registrations/user_footer"

app/views/items/edit.html.haml
= render partial: "form"

app/views/items/index.html.haml
.top-page
  = render "header"
  = render "main"
  = render "footer"

app/views/items/new.html.haml
= render partial: "form"

app/views/items/purchase_completed.html.haml
.single-container
  %header.single-header
    %h1
      =link_to root_path do
        = image_tag asset_path("material/logo/logo.png")
  .single-main
    .l-single-container
      %h2
        購入完了
      .single-main__container__form__frame
        .ec-info
          %span
            FURIMAからのメッセージ
          .ec-info__message
            ご利用ありがとうございます。商品の購入が完了しました。
            後ほど出品者からメールが届きますので、ご確認ください。
            またのご利用を待ちしております。
          .ec-info__img
            = image_tag "material/pict/aisatsu_arigatou.png"
        .item-info 
          -# .itme-info__img
          -#   = image_tag @item.images[0].image.url
          .item-info__name
            %span
              購入した商品：
            = @item.name
          .item-info__handling-time
            %span
              お届けまでの日数：
            = @item.handling_time.name
          .item-info__seller
            %span
              出品者
            = @item.user.nickname
        .return-to-top
          = link_to "買い物を続ける", root_path, class: "rtn btn"
        
  = render "devise/registrations/user_footer"

app/views/items/purchase_confirm.haml
.single-container
  %header.single-header
    %h1
      =link_to root_path do
        = image_tag asset_path("material/logo/logo.png")
  .single-main
    .l-single-container
      %h2
        購入内容の確認
      .single-main__container__form__frame
        .field.item-info
          .image
            = image_tag @item.images[0].image.url
          .info
            .name
              = @item.name
            .price
              税込
              = @item.shipping_fee.name
              %span
                ¥
                = @item.price
        .field.pay-amount
          %label
            支払い金額
          .amount
            ¥
            = @item.price
        .field.credit-card
          .sub-title
            支払い方法
          - if @card.present?
            %h3
              クレジットカード情報
            .card-number
              = "**** **** **** " + @card.last4
            %h3
              カードの有効期限
            .card-exp
              = @card.exp_month.to_s 
              = "/"
              = @card.exp_year.to_s.slice(2,3)
          - else
            = link_to "クレジットカードを登録してください", new_credit_card_path, data: {"turbolinks" => false}

        .field.address  
          .sub-title
            配送先
          - if current_user.address.present?
            .address
              = current_user.address.post_code
              = current_user.address.prefecture.name
              = current_user.address.city
              = current_user.address.building_name
          - else
            = link_to "配送先を登録してください", new_address_path
        .field.button
          - if @card.present? && current_user.address.present? && @item.status
            = link_to "購入する", purchase_item_path, method: :post, class: "buttun purchase"
          - else
            - unless @item.status
              %span
                この商品は売却済みです。現在購入はできません。
            - if @card.blank? || current_user.address.blank?
              %span
                商品の購入には、クレジットカード、及び配送先の登録が必要です。
              = link_to "購入する", "#", class: "buttun purchase disabled"
  = render "devise/registrations/user_footer"

app/views/items/show.html.haml
.top-page
  = render "header"
  %nav.breadCrumbs
    %ul
      %li
        = link_to "FURIMA", items_path
      %li
        = icon('fas', 'angle-right')
      %li
        = link_to @item.category.root.name, "#", class: "category-name"
      %li
        = icon('fas', 'angle-right')
      %li
        = link_to @item.category.parent.name, "#", class: "category-name"
      %li
        = icon('fas', 'angle-right')
      %li
        = link_to @item.category.name, "#", class: "category-name"
      %li
        = icon('fas', 'angle-right')
      %li
        %p
          = @item.name
  .Main
    .showMain
      .contentRight
        .topContent
          .itemBox
            %h2.itemBox__name
              = @item.name
            .itemBox__body
              %ul
                %li
                  - if @item.images[0].blank?
                    = image_tag "material/pict/no_images.png"
                  - else
                    = image_tag @item.images[0].image.url
                  .itemBox__body__images
                    - @item.images.each do |i|
                      = image_tag i.image.url, class: "image"
            .itemBox__price
              %span
                ¥
                = @item.price
              .itemBox__price-detail
                %span
                  (税込)
                %span
                  送料込み
            .itemDetail
              = @item.description
            .table
              %table
                %tbody
                  %tr
                    %th 出品者
                    %td
                      = @item.user.nickname
                  %tr
                    %th カテゴリー
                    %td
                      = link_to @item.category.root.name, "#", class: "category-name"
                      %br/
                      = link_to @item.category.parent.name, "#", class: "category-name"
                      %br/
                      = link_to @item.category.name, "#", class: "category-name"
                  %tr
                    %th ブランド
                    %td
                      = @item.brand
                  %tr
                    %th 商品のサイズ
                    %td
                      = @item.size.name
                  %tr
                    %th 商品の状態
                    %td 
                      = @item.condition.name
                  %tr
                    %th 配送料の負担
                    %td
                      = @item.shipping_fee.name
                  %tr
                    %th 発送元の地域
                    %td
                      = link_to @item.prefecture.name, "#"
                  %tr
                    %th 発送日の目安
                    %td
                      = @item.handling_time.name
            .optionalArea
              %ul
                %li#likeBtn.optionalBtn.likeBtn
                  = icon('fas', 'star')
                  お気に入り 0
              %ul.optional
                %li.optionalBtn
                  = link_to "#" do
                    = icon('fas', 'flag')
                    不適切な商品の通報
            .button
              - if @item.user == current_user
                = link_to "商品を編集する", edit_item_path, class: 'btn'
                = link_to "商品を削除する", item_path(@item), method: :delete, data: {confirm: "削除しますか？"}, class: 'btn'
              - else
                = link_to "購入画面へ進む", purchase_confirm_item_path(@item.id), class: 'btn'
          .commentBox
            %form#new_comment.new_comment{"accept-charset" => "UTF-8", :action => "#", :method => "post"}
              %textarea#comment_body{:name => "comment[body]", :required => "required"}
              %h5.noticeMsg
                .noticeMsg__top
                  相手のことを考え丁寧なコメントを心がけましょう。
                %br/
                不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %br/
              %button.Btn{:name => "button", :type => "submit"}
                = icon('fas', 'comment')
                コメントする
        %ul.links
          %li
            = link_to "#" do
              = icon('fas', 'angle-left')
              %span
              前の商品
          %li
            = link_to "#" do
              %span 後ろの商品
              = icon('fas', 'angle-right')
        .relatedItems
          = link_to "#{@item.category.root.name}をもっと見る", "#"
          .productLists
            = link_to "#" do
              %figure.productLists__img
                = image_tag "material/pict/a007.png"
              .productLists__body
                %h3.productLists__body__name product3
                .productLists__body__details
                  %ul
                    %li 30000円
                    %li
                      = icon('fas', 'star')
                      0
                  %p (税込)
  = render "footer"